version: 2.1

orbs:
  haskell: haskell-works/haskell-build@1.6.2
  github: haskell-works/github-release@1.2.1
  hackage: haskell-works/hackage@1.0.0

executors:
  cabal-build:
    parameters:
      ghc-version:
        description: GHC Version
        type: string
    docker:
      - image: quay.io/haskell_works/ghc-<< parameters.ghc-version >>
      - image: confluentinc/cp-zookeeper:5.1.0
        environment:
          ZOOKEEPER_CLIENT_PORT: 2181

      - image: confluentinc/cp-kafka:5.1.0
        environment:
          KAFKA_ZOOKEEPER_CONNECT: "localhost:2181"
          KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

commands:
  build-librdkafka:
    description: Build librdkafka
    steps:
      - restore_cache:
          key: cache--{{ .Environment.CACHE_VERSION }}--librdkafka--{{ checksum "scripts/build-librdkafka" }}
      - run:
          name: Build librdkafka
          command: ./scripts/build-librdkafka
      - save_cache:
          key: cache--{{ .Environment.CACHE_VERSION }}--librdkafka--{{ checksum "scripts/build-librdkafka" }}
          paths: .librdkafka

workflows:
  build-app-pipelines:
    jobs:
      - haskell/build:
          name: GHC 8.4.4
          executor:
            name: cabal-build
            ghc-version: 8.4.4
          before-build: [build-librdkafka]

      - haskell/build:
          name: GHC 8.6.3
          executor:
            name: cabal-build
            ghc-version: 8.6.3
          before-build: [build-librdkafka]

      - github/release-cabal:
          name: GitHub Release
          requires: [GHC 8.4.4, GHC 8.6.3]
          checkout: true
          filters:
            branches:
              only: master

      - hackage/upload:
          publish: true
          requires:
            - GitHub Release
          username: ${HACKAGE_USER}
          password: ${HACKAGE_PASS}
          filters:
            branches:
              only: master
